      <div class="masthead">
	<img src="logo.png"></img>
        <ul class="nav nav-justified">
          <li class="active"><a href="#">Home</a></li>
	  <li><a href="#">Citizens</a></li>
          <li><a href="#">Developers</a></li>
          <li><a href="#">Merchants</a></li>
          <li><a href="#">Governments</a></li>
          <li><a href="#">Investors</a></li>
          <li><a href="#">About Us</a></li>
        </ul>
      </div>

