      <div class="footer">
        <p>&copy; <a href="https://gnunet.org/ev">GNUnet e.V.</a> 2015</p>
        <p lang="en">This page was created using <a href="https://www.gnu.org/">Free Software</a> only.</p>
        <p lang="de">Diese Seite wurde allein durch Einsatz von <a href="https://www.gnu.org/">Freier Software</a> erstellt.</p>
        <p lang="fr">This page was created using <a href="https://www.gnu.org/">Free Software</a> only.</p>
        <p lang="it">This page was created using <a href="https://www.gnu.org/">Free Software</a> only.</p>
      </div>
    <script type="text/javascript">//<![CDATA[
      loadLang();
      activate_menu();
    //]]></script>
