      <div class="lang-slector">
        <tr><td>
        <a href="#"><img onclick="document.body.className='en'" src="images/gb.png" alt="English"></img></a>
        <a href="#"><img onclick="document.body.className='de'" src="images/de.png" alt="Deutsch"></img></a>
        <a href="#"><img onclick="document.body.className='fr'" src="images/fr.png" alt="Fran&ccedil;ais"></img></a>
	</td></tr>
      </div>
      <div class="masthead">
        <ul class="nav nav-justified">
          <li class="active"><a href="/">Home</a></li>
	  <li><a href="/citizens">Citizens</a></li>
          <li><a href="/merchants">Merchants</a></li>
          <li><a href="/governments">Governments</a></li>
          <li><a href="/developers">Developers</a></li>
          <li><a href="/investors">Investors</a></li>
          <li><a href="/about">About Us</a></li>
        </ul>
      </div>

