      <div class="row">
        <div class="row lang-slector">
          <a href="#" onclick="setLang('en');"><img src="images/gb.png" alt="English"></img></a>
          <a href="#" onclick="setLang('de');"><img src="images/de.png" alt="Deutsch"></img></a>
          <a href="#" onclick="setLang('fr');"><img src="images/fr.png" alt="Fran&ccedil;ais"></img></a>
        </div>
      </div>
      <div class="masthead">
        <ul class="nav nav-justified">
          <li id="m_main"><a href="/main.html">Home</a></li>
	  <li id="m_citizens"><a href="/citizens">Citizens</a></li>
          <li id="m_merchants"><a href="/merchants">Merchants</a></li>
          <li id="m_governments"><a href="/governments">Governments</a></li>
          <li id="m_developers"><a href="/developers">Developers</a></li>
          <li id="m_investors"><a href="/investors">Investors</a></li>
          <li id="m_about"><a href="/about">About Us</a></li>
        </ul>
      </div>

