      <div class="masthead">
        <ul class="nav nav-justified">
          <li class="active"><a href="/">Home</a></li>
	  <li><a href="/citizens">Citizens</a></li>
          <li><a href="/merchants">Merchants</a></li>
          <li><a href="/governments">Governments</a></li>
          <li><a href="/developers">Developers</a></li>
          <li><a href="/investors">Investors</a></li>
          <li><a href="/about/">About Us</a></li>
        </ul>
      </div>

